spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saul9402/servicio-items-config.git
          #si se va a configurar local se pone file:/// para windows y file:/ para linux
          #uri: file:///C:/Users/Cristopher Cerrillo/Desktop/config
          #las credenciales se deben poner cuando el repo es privado
          username: saul9402
          password: W8f!4%H%Y7xV5oqIW&
server:
  port: 8888
